name: log-exploration-api build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:

  build:
    name: api-build
    runs-on: ubuntu-20.04
    
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16.3' # The Go version to download (if necessary) and use.
    
    - name: Install dependencies
      run: |
        go mod download
        
    - name: Run Unit tests
      run: |
        make test
        
    - name: Install goveralls
      env:
        GO111MODULE: off
      run: go get github.com/mattn/goveralls
      
    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=covprofile -service=github
